### ISSUE TITLE
Very disapointing

### ISSUE THREAD

**Issue by JosepAlacid** [oneezy/monorepo#10]
1. Thank you for your work.
2. Keep it up or delete it.

```
Scope: all 12 workspace projects
apps/+stories                            |  WARN  deprecated sourcemap-codec@1.4.8
Packages: +856
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Packages are cloned from the content-addressable store to the virtual store.
  Content-addressable store is at: /home/user1/.local/share/pnpm/store/v3
  Virtual store is at:             node_modules/.pnpm
Progress: resolved 876, reused 392, downloaded 457, added 856, done
node_modules/.pnpm/svelte-preprocess@4.10.7_gqx7lw3sljhsd4bstor5m2aa2u/node_modules/svelte-preprocess: Running postinstall script, done in 74ms
node_modules/.pnpm/svelte-preprocess@4.10.7_wvrm32gd33klg3jid3dvetj6va/node_modules/svelte-preprocess: Running postinstall script, done in 69ms
node_modules/.pnpm/svelte-preprocess@4.10.7_awginupsaj455aehf5x365sh44/node_modules/svelte-preprocess: Running postinstall script, done in 70ms
node_modules/.pnpm/svelte-preprocess@4.10.7_oifjsu5oar4lzyaoppb2hxramu/node_modules/svelte-preprocess: Running postinstall script, done in 76ms
node_modules/.pnpm/esbuild@0.15.18/node_modules/esbuild: Running postinstall script, done in 288ms
node_modules/.pnpm/@sveltejs+kit@1.0.0-next.589_svelte@3.55.1+vite@3.2.5/node_modules/@sveltejs/kit: Running postinstall script, done in 1.2s
apps/docs preinstall$ pnpm exec inherit -u
│ Nothing needs to be updated.
└─ Done in 2.8s
apps/site preinstall$ pnpm exec inherit -u
│ Nothing needs to be updated.
└─ Done in 3.2s
. preinstall$ pnpm exec inherit -u
│ Nothing needs to be updated.
└─ Done in 2.9s
apps/+app preinstall$ pnpm exec inherit -u
│ Nothing needs to be updated.
└─ Done in 3.1s
apps/docs prepare$ svelte-kit sync
└─ Running...
. postinstall$ pnpm exec ./.sh/symlinks.sh
└─ Running...
apps/+app prepare$ svelte-kit sync
[1 lines collapsed]
│ file:///home/user/Projects/oneezy-delusion/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.589_svelte@3.55.1+vite@3.2.5/node_modules/@sveltejs/kit/src/exports/vite/dev/index.js:6
│          ^^^^^^^^^^^^
│ SyntaxError: The requested module 'vite' does not provide an export named 'isCSSRequest'
│     at ModuleJob._instantiate (node:internal/modules/esm/module_job:123:21)
│     at async ModuleJob.run (node:internal/modules/esm/module_job:189:5)
│     at async Promise.all (index 0)
│     at async ESMLoader.import (node:internal/modules/esm/loader:530:24)
│     at async load_config (file:///home/user/Projects/oneezy-delusion/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.589_svelte@3.55.1+vite@3.2.5/node_modules/@sveltejs/kit/src/core/config/index.js:61:17)
│     at async file:///home/user/Projects/oneezy-delusion/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.589_svelte@3.55.1+vite@3.2.5/node_modules/@sveltejs/kit/src/cli.js:36:19
│ Node.js v18.12.1
└─ Running...
└─ Failed in 1.1s at /home/user/Projects/oneezy-delusion/apps/+app
│ file:///home/user/Projects/oneezy-delusion/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.589_svelte@3.55.1+vite@3.2.5/node_modules/@sveltejs/kit/src/exports/vite/dev/index.js:6
│ import { isCSSRequest } from 'vite';
│          ^^^^^^^^^^^^
│ SyntaxError: The requested module 'vite' does not provide an export named 'isCSSRequest'
│     at ModuleJob._instantiate (node:internal/modules/esm/module_job:123:21)
│     at async ModuleJob.run (node:internal/modules/esm/module_job:189:5)
│     at async Promise.all (index 0)
│     at async ESMLoader.import (node:internal/modules/esm/loader:530:24)
│     at async load_config (file:///home/user/Projects/oneezy-delusion/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.589_svelte@3.55.1+vite@3.2.5/node_modules/@sveltejs/kit/src/core/config/index.js:61:17)
│     at async file:///home/user/Projects/oneezy-delusion/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.589_svelte@3.55.1+vite@3.2.5/node_modules/@sveltejs/kit/src/cli.js:36:19
│ Node.js v18.12.1
└─ Failed in 1.1s at /home/user/Projects/oneezy-delusion/apps/site
 ELIFECYCLE  Command failed with exit code 1.
```

**Comment by oneezy** [comment]
@JosepAlacid , 

1. Thankyou
2. Respectfully, this is an opensource project built for me and our team-

I'm in the process of updating this along with 10 other things. If you want to make a pull request or fork your own version to update, by all means you're free to do so. Otherwise please wait patiently. Updates are coming.

**Comment by JosepAlacid** [comment]
> Respectfully, this is an opensource project built for me and our team-

From your "readme" it seemed to me it has another target, but I must be wrong.
